/*
 * generated by Xtext 2.9.1
 */
package fr.inria.diverse.models2016.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProgramScopeProvider extends DelegatingScopeProvider {
}
