/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.models2016.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ProgramUiModule extends AbstractProgramUiModule {
}
