/**
 * generated by Xtext
 */
package fr.irisa.models.program.validation;

import fr.irisa.models.program.validation.AbstractProgramValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ProgramValidator extends AbstractProgramValidator {
}
