/*
 * generated by Xtext
 */
package fr.irisa.models.program;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProgramRuntimeModule extends fr.irisa.models.program.AbstractProgramRuntimeModule {

}
