<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="models2016" nsURI="http://www.example.org/models2016" nsPrefix="models2016">
  <eClassifiers xsi:type="ecore:EClass" name="Day">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" lowerBound="1"
        eType="#//WeekDay"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="#//DayDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        eType="#//Session" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="days" upperBound="-1" eType="#//Day"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingTime" eType="#//HourDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endingTime" eType="#//HourDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TalkSession" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chair" eType="#//Person"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="papers" upperBound="-1"
        eType="#//Paper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Panel" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="panelists" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moderators" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workshop" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tutorial" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoctoralSymposium" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EducatorSymposium" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reception" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clinic" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="papers" upperBound="-1"
        eType="#//Paper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="talkDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDay">
    <eLiterals name="Monday" literal="MONDAY"/>
    <eLiterals name="Tuesday" value="1" literal="TUESDAY"/>
    <eLiterals name="Wednesday" value="2" literal="WEDNESDAY"/>
    <eLiterals name="Thursday" value="3" literal="THURSDAY"/>
    <eLiterals name="Friday" value="4" literal="FRIDAY"/>
    <eLiterals name="Saturday" value="5" literal="SATURDAY"/>
    <eLiterals name="Sunday" value="6" literal="SUNDAY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homepage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//Track"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Track">
    <eLiterals name="PracticeAndInnovation" literal="PracticeAndInnovation"/>
    <eLiterals name="Research" value="1" literal="RESEARCH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lunch" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoffeeBreak" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EDataType" name="HourDataType" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DayDataType" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EClass" name="Meeting" eSuperTypes="#//Event"/>
</ecore:EPackage>
