/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.models2016.dsl.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.models2016.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ProgramUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.inria.diverse.models2016.dsl.Program");
	}

}
