/*
 * generated by Xtext
 */
package fr.irisa.models.program.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.irisa.models.program.services.ProgramGrammarAccess;

public class ProgramParser extends AbstractContentAssistParser {
	
	@Inject
	private ProgramGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.irisa.models.program.ui.contentassist.antlr.internal.InternalProgramParser createParser() {
		fr.irisa.models.program.ui.contentassist.antlr.internal.InternalProgramParser result = new fr.irisa.models.program.ui.contentassist.antlr.internal.InternalProgramParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getProgramAccess().getGroup_0(), "rule__Program__Group_0__0");
					put(grammarAccess.getProgramAccess().getGroup_0_2(), "rule__Program__Group_0_2__0");
					put(grammarAccess.getProgramAccess().getGroup_1(), "rule__Program__Group_1__0");
					put(grammarAccess.getDayAccess().getGroup(), "rule__Day__Group__0");
					put(grammarAccess.getDayAccess().getGroup_4(), "rule__Day__Group_4__0");
					put(grammarAccess.getSessionAccess().getGroup(), "rule__Session__Group__0");
					put(grammarAccess.getSessionAccess().getGroup_8(), "rule__Session__Group_8__0");
					put(grammarAccess.getTalkAccess().getGroup(), "rule__Talk__Group__0");
					put(grammarAccess.getTalkAccess().getGroup_6(), "rule__Talk__Group_6__0");
					put(grammarAccess.getTalkAccess().getGroup_6_2(), "rule__Talk__Group_6_2__0");
					put(grammarAccess.getProgramAccess().getRoomsAssignment_0_1(), "rule__Program__RoomsAssignment_0_1");
					put(grammarAccess.getProgramAccess().getRoomsAssignment_0_2_1(), "rule__Program__RoomsAssignment_0_2_1");
					put(grammarAccess.getProgramAccess().getDaysAssignment_1_1(), "rule__Program__DaysAssignment_1_1");
					put(grammarAccess.getProgramAccess().getDaysAssignment_1_2(), "rule__Program__DaysAssignment_1_2");
					put(grammarAccess.getRoomAccess().getNameAssignment(), "rule__Room__NameAssignment");
					put(grammarAccess.getDayAccess().getNameAssignment_3(), "rule__Day__NameAssignment_3");
					put(grammarAccess.getDayAccess().getSessionsAssignment_4_1(), "rule__Day__SessionsAssignment_4_1");
					put(grammarAccess.getDayAccess().getSessionsAssignment_4_2(), "rule__Day__SessionsAssignment_4_2");
					put(grammarAccess.getSessionAccess().getNameAssignment_3(), "rule__Session__NameAssignment_3");
					put(grammarAccess.getSessionAccess().getStartAssignment_5(), "rule__Session__StartAssignment_5");
					put(grammarAccess.getSessionAccess().getEndAssignment_7(), "rule__Session__EndAssignment_7");
					put(grammarAccess.getSessionAccess().getTalksAssignment_8_1(), "rule__Session__TalksAssignment_8_1");
					put(grammarAccess.getSessionAccess().getTalksAssignment_8_2(), "rule__Session__TalksAssignment_8_2");
					put(grammarAccess.getTalkAccess().getTilteAssignment_3(), "rule__Talk__TilteAssignment_3");
					put(grammarAccess.getTalkAccess().getRoomAssignment_5(), "rule__Talk__RoomAssignment_5");
					put(grammarAccess.getTalkAccess().getSpeakersAssignment_6_1(), "rule__Talk__SpeakersAssignment_6_1");
					put(grammarAccess.getTalkAccess().getSpeakersAssignment_6_2_1(), "rule__Talk__SpeakersAssignment_6_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.irisa.models.program.ui.contentassist.antlr.internal.InternalProgramParser typedParser = (fr.irisa.models.program.ui.contentassist.antlr.internal.InternalProgramParser) parser;
			typedParser.entryRuleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ProgramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProgramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
