/*
 * generated by Xtext
 */
package fr.irisa.models.program;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ProgramUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.irisa.models.program.ui.internal.ProgramActivator.getInstance().getInjector("fr.irisa.models.program.Program");
	}
	
}
