/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.models2016.dsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class ProgramOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
