/**
 * generated by Xtext
 */
package fr.irisa.models.program.ui.contentassist;

import fr.irisa.models.program.ui.contentassist.AbstractProgramProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ProgramProposalProvider extends AbstractProgramProposalProvider {
}
