/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.models2016.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ProgramGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ConferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Conference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConferenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTalkDurationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTalkDurationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTalkDurationEIntegerObjectParserRuleCall_3_0 = (RuleCall)cTalkDurationAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResourcesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cResourcesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cResourcesResourceParserRuleCall_4_1_0 = (RuleCall)cResourcesAssignment_4_1.eContents().get(0);
		private final Assignment cResourcesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cResourcesResourceParserRuleCall_4_2_0 = (RuleCall)cResourcesAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPapersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cPapersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cPapersPaperParserRuleCall_5_2_0 = (RuleCall)cPapersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cSemicolonKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cPapersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cPapersPaperParserRuleCall_5_3_1_0 = (RuleCall)cPapersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEventsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEventsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cEventsEventParserRuleCall_6_2_0 = (RuleCall)cEventsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cSemicolonKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cEventsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_6_3_1_0 = (RuleCall)cEventsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cProgramKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProgramAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cProgramProgramParserRuleCall_7_1_0 = (RuleCall)cProgramAssignment_7_1.eContents().get(0);
		
		//Conference:
		//	{Conference} name=EString
		//	'talk duration' talkDuration=EIntegerObject ('resources' resources+=Resource resources+=Resource*)? ('papers' '{'
		//	papers+=Paper (';' papers+=Paper)* '}')? ('events' '{' events+=Event (';' events+=Event)* '}')? ('program'
		//	program=Program)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Conference} name=EString 'talk duration' talkDuration=EIntegerObject ('resources' resources+=Resource
		//resources+=Resource*)? ('papers' '{' papers+=Paper (';' papers+=Paper)* '}')? ('events' '{' events+=Event (';'
		//events+=Event)* '}')? ('program' program=Program)?
		public Group getGroup() { return cGroup; }
		
		//{Conference}
		public Action getConferenceAction_0() { return cConferenceAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'talk duration'
		public Keyword getTalkDurationKeyword_2() { return cTalkDurationKeyword_2; }
		
		//talkDuration=EIntegerObject
		public Assignment getTalkDurationAssignment_3() { return cTalkDurationAssignment_3; }
		
		//EIntegerObject
		public RuleCall getTalkDurationEIntegerObjectParserRuleCall_3_0() { return cTalkDurationEIntegerObjectParserRuleCall_3_0; }
		
		//('resources' resources+=Resource resources+=Resource*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'resources'
		public Keyword getResourcesKeyword_4_0() { return cResourcesKeyword_4_0; }
		
		//resources+=Resource
		public Assignment getResourcesAssignment_4_1() { return cResourcesAssignment_4_1; }
		
		//Resource
		public RuleCall getResourcesResourceParserRuleCall_4_1_0() { return cResourcesResourceParserRuleCall_4_1_0; }
		
		//resources+=Resource*
		public Assignment getResourcesAssignment_4_2() { return cResourcesAssignment_4_2; }
		
		//Resource
		public RuleCall getResourcesResourceParserRuleCall_4_2_0() { return cResourcesResourceParserRuleCall_4_2_0; }
		
		//('papers' '{' papers+=Paper (';' papers+=Paper)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'papers'
		public Keyword getPapersKeyword_5_0() { return cPapersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//papers+=Paper
		public Assignment getPapersAssignment_5_2() { return cPapersAssignment_5_2; }
		
		//Paper
		public RuleCall getPapersPaperParserRuleCall_5_2_0() { return cPapersPaperParserRuleCall_5_2_0; }
		
		//(';' papers+=Paper)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//';'
		public Keyword getSemicolonKeyword_5_3_0() { return cSemicolonKeyword_5_3_0; }
		
		//papers+=Paper
		public Assignment getPapersAssignment_5_3_1() { return cPapersAssignment_5_3_1; }
		
		//Paper
		public RuleCall getPapersPaperParserRuleCall_5_3_1_0() { return cPapersPaperParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('events' '{' events+=Event (';' events+=Event)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'events'
		public Keyword getEventsKeyword_6_0() { return cEventsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//events+=Event
		public Assignment getEventsAssignment_6_2() { return cEventsAssignment_6_2; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_6_2_0() { return cEventsEventParserRuleCall_6_2_0; }
		
		//(';' events+=Event)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//';'
		public Keyword getSemicolonKeyword_6_3_0() { return cSemicolonKeyword_6_3_0; }
		
		//events+=Event
		public Assignment getEventsAssignment_6_3_1() { return cEventsAssignment_6_3_1; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_6_3_1_0() { return cEventsEventParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('program' program=Program)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'program'
		public Keyword getProgramKeyword_7_0() { return cProgramKeyword_7_0; }
		
		//program=Program
		public Assignment getProgramAssignment_7_1() { return cProgramAssignment_7_1; }
		
		//Program
		public RuleCall getProgramProgramParserRuleCall_7_1_0() { return cProgramProgramParserRuleCall_7_1_0; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Resource");
		private final RuleCall cRoomParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Resource:
		//	Room;
		@Override public ParserRule getRule() { return rule; }
		
		//Room
		public RuleCall getRoomParserRuleCall() { return cRoomParserRuleCall; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTalkSessionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPanelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cWorkshopParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTutorialParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDoctoralSymposiumParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cEducatorSymposiumParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cReceptionParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cClinicParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cLunchParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cCoffeeBreakParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cMeetingParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		private final RuleCall cSRCParserRuleCall_11 = (RuleCall)cAlternatives.eContents().get(11);
		private final RuleCall cPosterParserRuleCall_12 = (RuleCall)cAlternatives.eContents().get(12);
		private final RuleCall cKeyNoteParserRuleCall_13 = (RuleCall)cAlternatives.eContents().get(13);
		
		//Event:
		//	TalkSession | Panel | Workshop | Tutorial | DoctoralSymposium | EducatorSymposium | Reception | Clinic | Lunch |
		//	CoffeeBreak | Meeting | SRC | Poster | KeyNote;
		@Override public ParserRule getRule() { return rule; }
		
		//TalkSession | Panel | Workshop | Tutorial | DoctoralSymposium | EducatorSymposium | Reception | Clinic | Lunch |
		//CoffeeBreak | Meeting | SRC | Poster | KeyNote
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TalkSession
		public RuleCall getTalkSessionParserRuleCall_0() { return cTalkSessionParserRuleCall_0; }
		
		//Panel
		public RuleCall getPanelParserRuleCall_1() { return cPanelParserRuleCall_1; }
		
		//Workshop
		public RuleCall getWorkshopParserRuleCall_2() { return cWorkshopParserRuleCall_2; }
		
		//Tutorial
		public RuleCall getTutorialParserRuleCall_3() { return cTutorialParserRuleCall_3; }
		
		//DoctoralSymposium
		public RuleCall getDoctoralSymposiumParserRuleCall_4() { return cDoctoralSymposiumParserRuleCall_4; }
		
		//EducatorSymposium
		public RuleCall getEducatorSymposiumParserRuleCall_5() { return cEducatorSymposiumParserRuleCall_5; }
		
		//Reception
		public RuleCall getReceptionParserRuleCall_6() { return cReceptionParserRuleCall_6; }
		
		//Clinic
		public RuleCall getClinicParserRuleCall_7() { return cClinicParserRuleCall_7; }
		
		//Lunch
		public RuleCall getLunchParserRuleCall_8() { return cLunchParserRuleCall_8; }
		
		//CoffeeBreak
		public RuleCall getCoffeeBreakParserRuleCall_9() { return cCoffeeBreakParserRuleCall_9; }
		
		//Meeting
		public RuleCall getMeetingParserRuleCall_10() { return cMeetingParserRuleCall_10; }
		
		//SRC
		public RuleCall getSRCParserRuleCall_11() { return cSRCParserRuleCall_11; }
		
		//Poster
		public RuleCall getPosterParserRuleCall_12() { return cPosterParserRuleCall_12; }
		
		//KeyNote
		public RuleCall getKeyNoteParserRuleCall_13() { return cKeyNoteParserRuleCall_13; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.EString");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EString:
		//	STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProgramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cDaysAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cDaysDayParserRuleCall_2_0_0 = (RuleCall)cDaysAssignment_2_0.eContents().get(0);
		private final Assignment cDaysAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDaysDayParserRuleCall_2_1_0 = (RuleCall)cDaysAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Program:
		//	{Program} '{' (days+=Day days+=Day*)? '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Program} '{' (days+=Day days+=Day*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Program}
		public Action getProgramAction_0() { return cProgramAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(days+=Day days+=Day*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//days+=Day
		public Assignment getDaysAssignment_2_0() { return cDaysAssignment_2_0; }
		
		//Day
		public RuleCall getDaysDayParserRuleCall_2_0_0() { return cDaysDayParserRuleCall_2_0_0; }
		
		//days+=Day*
		public Assignment getDaysAssignment_2_1() { return cDaysAssignment_2_1; }
		
		//Day
		public RuleCall getDaysDayParserRuleCall_2_1_0() { return cDaysDayParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Room");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoomAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRoomKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCapacityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCapacityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCapacityEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cCapacityAssignment_3_1.eContents().get(0);
		
		//Room:
		//	{Room} 'room' name=EString ('capacity' capacity=EIntegerObject)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Room} 'room' name=EString ('capacity' capacity=EIntegerObject)?
		public Group getGroup() { return cGroup; }
		
		//{Room}
		public Action getRoomAction_0() { return cRoomAction_0; }
		
		//'room'
		public Keyword getRoomKeyword_1() { return cRoomKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('capacity' capacity=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'capacity'
		public Keyword getCapacityKeyword_3_0() { return cCapacityKeyword_3_0; }
		
		//capacity=EIntegerObject
		public Assignment getCapacityAssignment_3_1() { return cCapacityAssignment_3_1; }
		
		//EIntegerObject
		public RuleCall getCapacityEIntegerObjectParserRuleCall_3_1_0() { return cCapacityEIntegerObjectParserRuleCall_3_1_0; }
	}
	public class EIntegerObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.EIntegerObject");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EIntegerObject ecore::EIntegerObject:
		//	INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class DayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Day");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWeekdayAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cWeekdayWeekDayEnumRuleCall_0_0 = (RuleCall)cWeekdayAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cDateKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDateAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDateDayDataTypeParserRuleCall_1_1_0 = (RuleCall)cDateAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cSessionsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cSessionsSessionParserRuleCall_2_0_0 = (RuleCall)cSessionsAssignment_2_0.eContents().get(0);
		private final Assignment cSessionsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSessionsSessionParserRuleCall_2_1_0 = (RuleCall)cSessionsAssignment_2_1.eContents().get(0);
		
		//Day:
		//	weekday=WeekDay ('date' date=DayDataType)? (sessions+=Session sessions+=Session*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//weekday=WeekDay ('date' date=DayDataType)? (sessions+=Session sessions+=Session*)?
		public Group getGroup() { return cGroup; }
		
		//weekday=WeekDay
		public Assignment getWeekdayAssignment_0() { return cWeekdayAssignment_0; }
		
		//WeekDay
		public RuleCall getWeekdayWeekDayEnumRuleCall_0_0() { return cWeekdayWeekDayEnumRuleCall_0_0; }
		
		//('date' date=DayDataType)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'date'
		public Keyword getDateKeyword_1_0() { return cDateKeyword_1_0; }
		
		//date=DayDataType
		public Assignment getDateAssignment_1_1() { return cDateAssignment_1_1; }
		
		//DayDataType
		public RuleCall getDateDayDataTypeParserRuleCall_1_1_0() { return cDateDayDataTypeParserRuleCall_1_1_0; }
		
		//(sessions+=Session sessions+=Session*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//sessions+=Session
		public Assignment getSessionsAssignment_2_0() { return cSessionsAssignment_2_0; }
		
		//Session
		public RuleCall getSessionsSessionParserRuleCall_2_0_0() { return cSessionsSessionParserRuleCall_2_0_0; }
		
		//sessions+=Session*
		public Assignment getSessionsAssignment_2_1() { return cSessionsAssignment_2_1; }
		
		//Session
		public RuleCall getSessionsSessionParserRuleCall_2_1_0() { return cSessionsSessionParserRuleCall_2_1_0; }
	}
	public class DayDataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.DayDataType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//DayDataType ecore::EDate:
		//	INT '.' INT '.' INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
	}
	public class HourDataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.HourDataType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//HourDataType ecore::EDate:
		//	INT ':' INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT ':' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class SessionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Session");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSessionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cStartingTimeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStartingTimeHourDataTypeParserRuleCall_1_0 = (RuleCall)cStartingTimeAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEndingTimeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEndingTimeHourDataTypeParserRuleCall_3_0 = (RuleCall)cEndingTimeAssignment_3.eContents().get(0);
		private final Keyword cInKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRoomAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cRoomRoomCrossReference_5_0 = (CrossReference)cRoomAssignment_5.eContents().get(0);
		private final RuleCall cRoomRoomEStringParserRuleCall_5_0_1 = (RuleCall)cRoomRoomCrossReference_5_0.eContents().get(1);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEventsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cEventsEventCrossReference_7_0 = (CrossReference)cEventsAssignment_7.eContents().get(0);
		private final RuleCall cEventsEventEStringParserRuleCall_7_0_1 = (RuleCall)cEventsEventCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cEventsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cEventsEventCrossReference_8_1_0 = (CrossReference)cEventsAssignment_8_1.eContents().get(0);
		private final RuleCall cEventsEventEStringParserRuleCall_8_1_0_1 = (RuleCall)cEventsEventCrossReference_8_1_0.eContents().get(1);
		
		//Session:
		//	{Session} startingTime=HourDataType '-' endingTime=HourDataType 'in'
		//	room=[Room|EString] ':'
		//	events+=[Event|EString] (',' events+=[Event|EString])*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Session} startingTime=HourDataType '-' endingTime=HourDataType 'in' room=[Room|EString] ':' events+=[Event|EString]
		//(',' events+=[Event|EString])*
		public Group getGroup() { return cGroup; }
		
		//{Session}
		public Action getSessionAction_0() { return cSessionAction_0; }
		
		//startingTime=HourDataType
		public Assignment getStartingTimeAssignment_1() { return cStartingTimeAssignment_1; }
		
		//HourDataType
		public RuleCall getStartingTimeHourDataTypeParserRuleCall_1_0() { return cStartingTimeHourDataTypeParserRuleCall_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_2() { return cHyphenMinusKeyword_2; }
		
		//endingTime=HourDataType
		public Assignment getEndingTimeAssignment_3() { return cEndingTimeAssignment_3; }
		
		//HourDataType
		public RuleCall getEndingTimeHourDataTypeParserRuleCall_3_0() { return cEndingTimeHourDataTypeParserRuleCall_3_0; }
		
		//'in'
		public Keyword getInKeyword_4() { return cInKeyword_4; }
		
		//room=[Room|EString]
		public Assignment getRoomAssignment_5() { return cRoomAssignment_5; }
		
		//[Room|EString]
		public CrossReference getRoomRoomCrossReference_5_0() { return cRoomRoomCrossReference_5_0; }
		
		//EString
		public RuleCall getRoomRoomEStringParserRuleCall_5_0_1() { return cRoomRoomEStringParserRuleCall_5_0_1; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//events+=[Event|EString]
		public Assignment getEventsAssignment_7() { return cEventsAssignment_7; }
		
		//[Event|EString]
		public CrossReference getEventsEventCrossReference_7_0() { return cEventsEventCrossReference_7_0; }
		
		//EString
		public RuleCall getEventsEventEStringParserRuleCall_7_0_1() { return cEventsEventEStringParserRuleCall_7_0_1; }
		
		//(',' events+=[Event|EString])*
		public Group getGroup_8() { return cGroup_8; }
		
		//','
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//events+=[Event|EString]
		public Assignment getEventsAssignment_8_1() { return cEventsAssignment_8_1; }
		
		//[Event|EString]
		public CrossReference getEventsEventCrossReference_8_1_0() { return cEventsEventCrossReference_8_1_0; }
		
		//EString
		public RuleCall getEventsEventEStringParserRuleCall_8_1_0_1() { return cEventsEventEStringParserRuleCall_8_1_0_1; }
	}
	public class TalkSessionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.TalkSession");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTalkSessionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cChairKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cChairAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cChairPersonParserRuleCall_2_1_0 = (RuleCall)cChairAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAbstractKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAbstractAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_3_1_0 = (RuleCall)cAbstractAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPapersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPapersAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cPapersPaperCrossReference_4_1_0 = (CrossReference)cPapersAssignment_4_1.eContents().get(0);
		private final RuleCall cPapersPaperEStringParserRuleCall_4_1_0_1 = (RuleCall)cPapersPaperCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cPapersAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cPapersPaperCrossReference_4_2_1_0 = (CrossReference)cPapersAssignment_4_2_1.eContents().get(0);
		private final RuleCall cPapersPaperEStringParserRuleCall_4_2_1_0_1 = (RuleCall)cPapersPaperCrossReference_4_2_1_0.eContents().get(1);
		
		//TalkSession:
		//	'TalkSession'
		//	name=EString ('chair' chair=Person)? ('abstract' abstract=EString)? ('papers' papers+=[Paper|EString] (','
		//	papers+=[Paper|EString])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'TalkSession' name=EString ('chair' chair=Person)? ('abstract' abstract=EString)? ('papers' papers+=[Paper|EString] (','
		//papers+=[Paper|EString])*)?
		public Group getGroup() { return cGroup; }
		
		//'TalkSession'
		public Keyword getTalkSessionKeyword_0() { return cTalkSessionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('chair' chair=Person)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'chair'
		public Keyword getChairKeyword_2_0() { return cChairKeyword_2_0; }
		
		//chair=Person
		public Assignment getChairAssignment_2_1() { return cChairAssignment_2_1; }
		
		//Person
		public RuleCall getChairPersonParserRuleCall_2_1_0() { return cChairPersonParserRuleCall_2_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'abstract'
		public Keyword getAbstractKeyword_3_0() { return cAbstractKeyword_3_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_3_1() { return cAbstractAssignment_3_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_3_1_0() { return cAbstractEStringParserRuleCall_3_1_0; }
		
		//('papers' papers+=[Paper|EString] (',' papers+=[Paper|EString])*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'papers'
		public Keyword getPapersKeyword_4_0() { return cPapersKeyword_4_0; }
		
		//papers+=[Paper|EString]
		public Assignment getPapersAssignment_4_1() { return cPapersAssignment_4_1; }
		
		//[Paper|EString]
		public CrossReference getPapersPaperCrossReference_4_1_0() { return cPapersPaperCrossReference_4_1_0; }
		
		//EString
		public RuleCall getPapersPaperEStringParserRuleCall_4_1_0_1() { return cPapersPaperEStringParserRuleCall_4_1_0_1; }
		
		//(',' papers+=[Paper|EString])*
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//','
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }
		
		//papers+=[Paper|EString]
		public Assignment getPapersAssignment_4_2_1() { return cPapersAssignment_4_2_1; }
		
		//[Paper|EString]
		public CrossReference getPapersPaperCrossReference_4_2_1_0() { return cPapersPaperCrossReference_4_2_1_0; }
		
		//EString
		public RuleCall getPapersPaperEStringParserRuleCall_4_2_1_0_1() { return cPapersPaperEStringParserRuleCall_4_2_1_0_1; }
	}
	public class PanelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Panel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPanelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPanelistsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPanelistsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPanelistsPersonParserRuleCall_3_1_0 = (RuleCall)cPanelistsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cPanelistsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cPanelistsPersonParserRuleCall_3_2_1_0 = (RuleCall)cPanelistsAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModeratorsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cModeratorsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cModeratorsPersonParserRuleCall_4_1_0 = (RuleCall)cModeratorsAssignment_4_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cModeratorsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final RuleCall cModeratorsPersonParserRuleCall_4_2_1_0 = (RuleCall)cModeratorsAssignment_4_2_1.eContents().get(0);
		
		//Panel:
		//	'Panel'
		//	name=EString ('abstract' abstract=EString)? ('panelists' panelists+=Person (',' panelists+=Person)*)? ('moderators'
		//	moderators+=Person (',' moderators+=Person)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Panel' name=EString ('abstract' abstract=EString)? ('panelists' panelists+=Person (',' panelists+=Person)*)?
		//('moderators' moderators+=Person (',' moderators+=Person)*)?
		public Group getGroup() { return cGroup; }
		
		//'Panel'
		public Keyword getPanelKeyword_0() { return cPanelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('panelists' panelists+=Person (',' panelists+=Person)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'panelists'
		public Keyword getPanelistsKeyword_3_0() { return cPanelistsKeyword_3_0; }
		
		//panelists+=Person
		public Assignment getPanelistsAssignment_3_1() { return cPanelistsAssignment_3_1; }
		
		//Person
		public RuleCall getPanelistsPersonParserRuleCall_3_1_0() { return cPanelistsPersonParserRuleCall_3_1_0; }
		
		//(',' panelists+=Person)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }
		
		//panelists+=Person
		public Assignment getPanelistsAssignment_3_2_1() { return cPanelistsAssignment_3_2_1; }
		
		//Person
		public RuleCall getPanelistsPersonParserRuleCall_3_2_1_0() { return cPanelistsPersonParserRuleCall_3_2_1_0; }
		
		//('moderators' moderators+=Person (',' moderators+=Person)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'moderators'
		public Keyword getModeratorsKeyword_4_0() { return cModeratorsKeyword_4_0; }
		
		//moderators+=Person
		public Assignment getModeratorsAssignment_4_1() { return cModeratorsAssignment_4_1; }
		
		//Person
		public RuleCall getModeratorsPersonParserRuleCall_4_1_0() { return cModeratorsPersonParserRuleCall_4_1_0; }
		
		//(',' moderators+=Person)*
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//','
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }
		
		//moderators+=Person
		public Assignment getModeratorsAssignment_4_2_1() { return cModeratorsAssignment_4_2_1; }
		
		//Person
		public RuleCall getModeratorsPersonParserRuleCall_4_2_1_0() { return cModeratorsPersonParserRuleCall_4_2_1_0; }
	}
	public class SRCElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.SRC");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSRCKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//SRC:
		//	'SRC'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'SRC' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'SRC'
		public Keyword getSRCKeyword_0() { return cSRCKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class PosterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Poster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPosterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//Poster:
		//	'Poster'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Poster' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'Poster'
		public Keyword getPosterKeyword_0() { return cPosterKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class KeyNoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.KeyNote");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKeyNoteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSpeakerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSpeakerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSpeakerPersonParserRuleCall_3_1_0 = (RuleCall)cSpeakerAssignment_3_1.eContents().get(0);
		
		//KeyNote:
		//	'KeyNote'
		//	name=EString ('abstract' abstract=EString)? ('speaker' speaker=Person)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'KeyNote' name=EString ('abstract' abstract=EString)? ('speaker' speaker=Person)?
		public Group getGroup() { return cGroup; }
		
		//'KeyNote'
		public Keyword getKeyNoteKeyword_0() { return cKeyNoteKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('speaker' speaker=Person)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'speaker'
		public Keyword getSpeakerKeyword_3_0() { return cSpeakerKeyword_3_0; }
		
		//speaker=Person
		public Assignment getSpeakerAssignment_3_1() { return cSpeakerAssignment_3_1; }
		
		//Person
		public RuleCall getSpeakerPersonParserRuleCall_3_1_0() { return cSpeakerPersonParserRuleCall_3_1_0; }
	}
	public class WorkshopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Workshop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkshopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUrlKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUrlAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_3_1_0 = (RuleCall)cUrlAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFullNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFullNameEStringParserRuleCall_4_1_0 = (RuleCall)cFullNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOrganizersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOrganizersAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_5_1_0 = (RuleCall)cOrganizersAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cOrganizersAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_5_2_1_0 = (RuleCall)cOrganizersAssignment_5_2_1.eContents().get(0);
		
		//Workshop:
		//	'Workshop'
		//	name=EString ('abstract' abstract=EString)? ('url' url=EString)? ('name' fullName=EString)? ('organizers'
		//	organizers+=Person (',' organizers+=Person)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Workshop' name=EString ('abstract' abstract=EString)? ('url' url=EString)? ('name' fullName=EString)? ('organizers'
		//organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup() { return cGroup; }
		
		//'Workshop'
		public Keyword getWorkshopKeyword_0() { return cWorkshopKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('url' url=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'url'
		public Keyword getUrlKeyword_3_0() { return cUrlKeyword_3_0; }
		
		//url=EString
		public Assignment getUrlAssignment_3_1() { return cUrlAssignment_3_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_1_0() { return cUrlEStringParserRuleCall_3_1_0; }
		
		//('name' fullName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'name'
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }
		
		//fullName=EString
		public Assignment getFullNameAssignment_4_1() { return cFullNameAssignment_4_1; }
		
		//EString
		public RuleCall getFullNameEStringParserRuleCall_4_1_0() { return cFullNameEStringParserRuleCall_4_1_0; }
		
		//('organizers' organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'organizers'
		public Keyword getOrganizersKeyword_5_0() { return cOrganizersKeyword_5_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_5_1() { return cOrganizersAssignment_5_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_5_1_0() { return cOrganizersPersonParserRuleCall_5_1_0; }
		
		//(',' organizers+=Person)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//','
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_5_2_1() { return cOrganizersAssignment_5_2_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_5_2_1_0() { return cOrganizersPersonParserRuleCall_5_2_1_0; }
	}
	public class TutorialElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Tutorial");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTutorialKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOrganizersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_1_0 = (RuleCall)cOrganizersAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_2_1_0 = (RuleCall)cOrganizersAssignment_3_2_1.eContents().get(0);
		
		//Tutorial:
		//	'Tutorial'
		//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Tutorial' name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup() { return cGroup; }
		
		//'Tutorial'
		public Keyword getTutorialKeyword_0() { return cTutorialKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('organizers' organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'organizers'
		public Keyword getOrganizersKeyword_3_0() { return cOrganizersKeyword_3_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_1() { return cOrganizersAssignment_3_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_1_0() { return cOrganizersPersonParserRuleCall_3_1_0; }
		
		//(',' organizers+=Person)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_2_1() { return cOrganizersAssignment_3_2_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_2_1_0() { return cOrganizersPersonParserRuleCall_3_2_1_0; }
	}
	public class DoctoralSymposiumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.DoctoralSymposium");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDoctoralSymposiumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOrganizersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_1_0 = (RuleCall)cOrganizersAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_2_1_0 = (RuleCall)cOrganizersAssignment_3_2_1.eContents().get(0);
		
		//DoctoralSymposium:
		//	'DoctoralSymposium'
		//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'DoctoralSymposium' name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (','
		//organizers+=Person)*)?
		public Group getGroup() { return cGroup; }
		
		//'DoctoralSymposium'
		public Keyword getDoctoralSymposiumKeyword_0() { return cDoctoralSymposiumKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('organizers' organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'organizers'
		public Keyword getOrganizersKeyword_3_0() { return cOrganizersKeyword_3_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_1() { return cOrganizersAssignment_3_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_1_0() { return cOrganizersPersonParserRuleCall_3_1_0; }
		
		//(',' organizers+=Person)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_2_1() { return cOrganizersAssignment_3_2_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_2_1_0() { return cOrganizersPersonParserRuleCall_3_2_1_0; }
	}
	public class EducatorSymposiumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.EducatorSymposium");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEducatorSymposiumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOrganizersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_1_0 = (RuleCall)cOrganizersAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cOrganizersAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cOrganizersPersonParserRuleCall_3_2_1_0 = (RuleCall)cOrganizersAssignment_3_2_1.eContents().get(0);
		
		//EducatorSymposium:
		//	'EducatorSymposium'
		//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'EducatorSymposium' name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (','
		//organizers+=Person)*)?
		public Group getGroup() { return cGroup; }
		
		//'EducatorSymposium'
		public Keyword getEducatorSymposiumKeyword_0() { return cEducatorSymposiumKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
		
		//('organizers' organizers+=Person (',' organizers+=Person)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'organizers'
		public Keyword getOrganizersKeyword_3_0() { return cOrganizersKeyword_3_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_1() { return cOrganizersAssignment_3_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_1_0() { return cOrganizersPersonParserRuleCall_3_1_0; }
		
		//(',' organizers+=Person)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }
		
		//organizers+=Person
		public Assignment getOrganizersAssignment_3_2_1() { return cOrganizersAssignment_3_2_1; }
		
		//Person
		public RuleCall getOrganizersPersonParserRuleCall_3_2_1_0() { return cOrganizersPersonParserRuleCall_3_2_1_0; }
	}
	public class ReceptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Reception");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReceptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//Reception:
		//	'Reception'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Reception' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'Reception'
		public Keyword getReceptionKeyword_0() { return cReceptionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class ClinicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Clinic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClinicKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//Clinic:
		//	'Clinic'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Clinic' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'Clinic'
		public Keyword getClinicKeyword_0() { return cClinicKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class LunchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Lunch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLunchKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//Lunch:
		//	'Lunch'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Lunch' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'Lunch'
		public Keyword getLunchKeyword_0() { return cLunchKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class CoffeeBreakElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.CoffeeBreak");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCoffeeBreakKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//CoffeeBreak:
		//	'CoffeeBreak'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'CoffeeBreak' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'CoffeeBreak'
		public Keyword getCoffeeBreakKeyword_0() { return cCoffeeBreakKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class MeetingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Meeting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMeetingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAbstractKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAbstractAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_2_1_0 = (RuleCall)cAbstractAssignment_2_1.eContents().get(0);
		
		//Meeting:
		//	'Meeting'
		//	name=EString ('abstract' abstract=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Meeting' name=EString ('abstract' abstract=EString)?
		public Group getGroup() { return cGroup; }
		
		//'Meeting'
		public Keyword getMeetingKeyword_0() { return cMeetingKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'abstract'
		public Keyword getAbstractKeyword_2_0() { return cAbstractKeyword_2_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_2_1() { return cAbstractAssignment_2_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_2_1_0() { return cAbstractEStringParserRuleCall_2_1_0; }
	}
	public class PaperElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Paper");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPaperAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cAuthorsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAuthorsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAuthorsPersonParserRuleCall_3_0 = (RuleCall)cAuthorsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAuthorsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAuthorsPersonParserRuleCall_4_1_0 = (RuleCall)cAuthorsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAbstractKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAbstractAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAbstractEStringParserRuleCall_5_1_0 = (RuleCall)cAbstractAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPreprintKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPreprintAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPreprintEStringParserRuleCall_6_1_0 = (RuleCall)cPreprintAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cKindKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cKindAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cKindTrackEnumRuleCall_7_1_0 = (RuleCall)cKindAssignment_7_1.eContents().get(0);
		
		//Paper:
		//	{Paper} name=EString
		//	'authors' authors+=Person (',' authors+=Person)* ('abstract' abstract=EString)? ('preprint' preprint=EString)? ('kind'
		//	kind=Track)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Paper} name=EString 'authors' authors+=Person (',' authors+=Person)* ('abstract' abstract=EString)? ('preprint'
		//preprint=EString)? ('kind' kind=Track)?
		public Group getGroup() { return cGroup; }
		
		//{Paper}
		public Action getPaperAction_0() { return cPaperAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'authors'
		public Keyword getAuthorsKeyword_2() { return cAuthorsKeyword_2; }
		
		//authors+=Person
		public Assignment getAuthorsAssignment_3() { return cAuthorsAssignment_3; }
		
		//Person
		public RuleCall getAuthorsPersonParserRuleCall_3_0() { return cAuthorsPersonParserRuleCall_3_0; }
		
		//(',' authors+=Person)*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//authors+=Person
		public Assignment getAuthorsAssignment_4_1() { return cAuthorsAssignment_4_1; }
		
		//Person
		public RuleCall getAuthorsPersonParserRuleCall_4_1_0() { return cAuthorsPersonParserRuleCall_4_1_0; }
		
		//('abstract' abstract=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'abstract'
		public Keyword getAbstractKeyword_5_0() { return cAbstractKeyword_5_0; }
		
		//abstract=EString
		public Assignment getAbstractAssignment_5_1() { return cAbstractAssignment_5_1; }
		
		//EString
		public RuleCall getAbstractEStringParserRuleCall_5_1_0() { return cAbstractEStringParserRuleCall_5_1_0; }
		
		//('preprint' preprint=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'preprint'
		public Keyword getPreprintKeyword_6_0() { return cPreprintKeyword_6_0; }
		
		//preprint=EString
		public Assignment getPreprintAssignment_6_1() { return cPreprintAssignment_6_1; }
		
		//EString
		public RuleCall getPreprintEStringParserRuleCall_6_1_0() { return cPreprintEStringParserRuleCall_6_1_0; }
		
		//('kind' kind=Track)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'kind'
		public Keyword getKindKeyword_7_0() { return cKindKeyword_7_0; }
		
		//kind=Track
		public Assignment getKindAssignment_7_1() { return cKindAssignment_7_1; }
		
		//Track
		public RuleCall getKindTrackEnumRuleCall_7_1_0() { return cKindTrackEnumRuleCall_7_1_0; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPersonAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cEmailKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cEmailAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cEmailEStringParserRuleCall_2_1_0 = (RuleCall)cEmailAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cHomepageKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cHomepageAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cHomepageEStringParserRuleCall_3_1_0 = (RuleCall)cHomepageAssignment_3_1.eContents().get(0);
		
		//Person:
		//	{Person} name=EString ('email' email=EString)? ('homepage' homepage=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Person} name=EString ('email' email=EString)? ('homepage' homepage=EString)?
		public Group getGroup() { return cGroup; }
		
		//{Person}
		public Action getPersonAction_0() { return cPersonAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('email' email=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'email'
		public Keyword getEmailKeyword_2_0() { return cEmailKeyword_2_0; }
		
		//email=EString
		public Assignment getEmailAssignment_2_1() { return cEmailAssignment_2_1; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_2_1_0() { return cEmailEStringParserRuleCall_2_1_0; }
		
		//('homepage' homepage=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'homepage'
		public Keyword getHomepageKeyword_3_0() { return cHomepageKeyword_3_0; }
		
		//homepage=EString
		public Assignment getHomepageAssignment_3_1() { return cHomepageAssignment_3_1; }
		
		//EString
		public RuleCall getHomepageEStringParserRuleCall_3_1_0() { return cHomepageEStringParserRuleCall_3_1_0; }
	}
	
	public class WeekDayElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.WeekDay");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMondayEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMondayMondayKeyword_0_0 = (Keyword)cMondayEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTuesdayEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTuesdayTuesdayKeyword_1_0 = (Keyword)cTuesdayEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWednesdayEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWednesdayWednesdayKeyword_2_0 = (Keyword)cWednesdayEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cThursdayEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cThursdayThursdayKeyword_3_0 = (Keyword)cThursdayEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cFridayEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cFridayFridayKeyword_4_0 = (Keyword)cFridayEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSaturdayEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSaturdaySaturdayKeyword_5_0 = (Keyword)cSaturdayEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSundayEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSundaySundayKeyword_6_0 = (Keyword)cSundayEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum WeekDay:
		//	Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday;
		public EnumRule getRule() { return rule; }
		
		//Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Monday
		public EnumLiteralDeclaration getMondayEnumLiteralDeclaration_0() { return cMondayEnumLiteralDeclaration_0; }
		
		//'Monday'
		public Keyword getMondayMondayKeyword_0_0() { return cMondayMondayKeyword_0_0; }
		
		//Tuesday
		public EnumLiteralDeclaration getTuesdayEnumLiteralDeclaration_1() { return cTuesdayEnumLiteralDeclaration_1; }
		
		//'Tuesday'
		public Keyword getTuesdayTuesdayKeyword_1_0() { return cTuesdayTuesdayKeyword_1_0; }
		
		//Wednesday
		public EnumLiteralDeclaration getWednesdayEnumLiteralDeclaration_2() { return cWednesdayEnumLiteralDeclaration_2; }
		
		//'Wednesday'
		public Keyword getWednesdayWednesdayKeyword_2_0() { return cWednesdayWednesdayKeyword_2_0; }
		
		//Thursday
		public EnumLiteralDeclaration getThursdayEnumLiteralDeclaration_3() { return cThursdayEnumLiteralDeclaration_3; }
		
		//'Thursday'
		public Keyword getThursdayThursdayKeyword_3_0() { return cThursdayThursdayKeyword_3_0; }
		
		//Friday
		public EnumLiteralDeclaration getFridayEnumLiteralDeclaration_4() { return cFridayEnumLiteralDeclaration_4; }
		
		//'Friday'
		public Keyword getFridayFridayKeyword_4_0() { return cFridayFridayKeyword_4_0; }
		
		//Saturday
		public EnumLiteralDeclaration getSaturdayEnumLiteralDeclaration_5() { return cSaturdayEnumLiteralDeclaration_5; }
		
		//'Saturday'
		public Keyword getSaturdaySaturdayKeyword_5_0() { return cSaturdaySaturdayKeyword_5_0; }
		
		//Sunday
		public EnumLiteralDeclaration getSundayEnumLiteralDeclaration_6() { return cSundayEnumLiteralDeclaration_6; }
		
		//'Sunday'
		public Keyword getSundaySundayKeyword_6_0() { return cSundaySundayKeyword_6_0; }
	}
	public class TrackElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.diverse.models2016.dsl.Program.Track");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPracticeAndInnovationEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPracticeAndInnovationPracticeAndInnovationKeyword_0_0 = (Keyword)cPracticeAndInnovationEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cResearchEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cResearchResearchKeyword_1_0 = (Keyword)cResearchEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Track:
		//	PracticeAndInnovation='Practice and Innovation' | Research;
		public EnumRule getRule() { return rule; }
		
		//PracticeAndInnovation='Practice and Innovation' | Research
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PracticeAndInnovation='Practice and Innovation'
		public EnumLiteralDeclaration getPracticeAndInnovationEnumLiteralDeclaration_0() { return cPracticeAndInnovationEnumLiteralDeclaration_0; }
		
		//'Practice and Innovation'
		public Keyword getPracticeAndInnovationPracticeAndInnovationKeyword_0_0() { return cPracticeAndInnovationPracticeAndInnovationKeyword_0_0; }
		
		//Research
		public EnumLiteralDeclaration getResearchEnumLiteralDeclaration_1() { return cResearchEnumLiteralDeclaration_1; }
		
		//'Research'
		public Keyword getResearchResearchKeyword_1_0() { return cResearchResearchKeyword_1_0; }
	}
	
	private final ConferenceElements pConference;
	private final ResourceElements pResource;
	private final EventElements pEvent;
	private final EStringElements pEString;
	private final ProgramElements pProgram;
	private final RoomElements pRoom;
	private final EIntegerObjectElements pEIntegerObject;
	private final DayElements pDay;
	private final WeekDayElements eWeekDay;
	private final DayDataTypeElements pDayDataType;
	private final HourDataTypeElements pHourDataType;
	private final SessionElements pSession;
	private final TalkSessionElements pTalkSession;
	private final PanelElements pPanel;
	private final SRCElements pSRC;
	private final PosterElements pPoster;
	private final KeyNoteElements pKeyNote;
	private final WorkshopElements pWorkshop;
	private final TutorialElements pTutorial;
	private final DoctoralSymposiumElements pDoctoralSymposium;
	private final EducatorSymposiumElements pEducatorSymposium;
	private final ReceptionElements pReception;
	private final ClinicElements pClinic;
	private final LunchElements pLunch;
	private final CoffeeBreakElements pCoffeeBreak;
	private final MeetingElements pMeeting;
	private final PaperElements pPaper;
	private final PersonElements pPerson;
	private final TrackElements eTrack;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ProgramGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pConference = new ConferenceElements();
		this.pResource = new ResourceElements();
		this.pEvent = new EventElements();
		this.pEString = new EStringElements();
		this.pProgram = new ProgramElements();
		this.pRoom = new RoomElements();
		this.pEIntegerObject = new EIntegerObjectElements();
		this.pDay = new DayElements();
		this.eWeekDay = new WeekDayElements();
		this.pDayDataType = new DayDataTypeElements();
		this.pHourDataType = new HourDataTypeElements();
		this.pSession = new SessionElements();
		this.pTalkSession = new TalkSessionElements();
		this.pPanel = new PanelElements();
		this.pSRC = new SRCElements();
		this.pPoster = new PosterElements();
		this.pKeyNote = new KeyNoteElements();
		this.pWorkshop = new WorkshopElements();
		this.pTutorial = new TutorialElements();
		this.pDoctoralSymposium = new DoctoralSymposiumElements();
		this.pEducatorSymposium = new EducatorSymposiumElements();
		this.pReception = new ReceptionElements();
		this.pClinic = new ClinicElements();
		this.pLunch = new LunchElements();
		this.pCoffeeBreak = new CoffeeBreakElements();
		this.pMeeting = new MeetingElements();
		this.pPaper = new PaperElements();
		this.pPerson = new PersonElements();
		this.eTrack = new TrackElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.inria.diverse.models2016.dsl.Program".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Conference:
	//	{Conference} name=EString
	//	'talk duration' talkDuration=EIntegerObject ('resources' resources+=Resource resources+=Resource*)? ('papers' '{'
	//	papers+=Paper (';' papers+=Paper)* '}')? ('events' '{' events+=Event (';' events+=Event)* '}')? ('program'
	//	program=Program)?;
	public ConferenceElements getConferenceAccess() {
		return pConference;
	}
	
	public ParserRule getConferenceRule() {
		return getConferenceAccess().getRule();
	}
	
	//Resource:
	//	Room;
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//Event:
	//	TalkSession | Panel | Workshop | Tutorial | DoctoralSymposium | EducatorSymposium | Reception | Clinic | Lunch |
	//	CoffeeBreak | Meeting | SRC | Poster | KeyNote;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//EString:
	//	STRING;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Program:
	//	{Program} '{' (days+=Day days+=Day*)? '}';
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Room:
	//	{Room} 'room' name=EString ('capacity' capacity=EIntegerObject)?;
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//EIntegerObject ecore::EIntegerObject:
	//	INT
	public EIntegerObjectElements getEIntegerObjectAccess() {
		return pEIntegerObject;
	}
	
	public ParserRule getEIntegerObjectRule() {
		return getEIntegerObjectAccess().getRule();
	}
	
	//Day:
	//	weekday=WeekDay ('date' date=DayDataType)? (sessions+=Session sessions+=Session*)?;
	public DayElements getDayAccess() {
		return pDay;
	}
	
	public ParserRule getDayRule() {
		return getDayAccess().getRule();
	}
	
	//enum WeekDay:
	//	Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday;
	public WeekDayElements getWeekDayAccess() {
		return eWeekDay;
	}
	
	public EnumRule getWeekDayRule() {
		return getWeekDayAccess().getRule();
	}
	
	//DayDataType ecore::EDate:
	//	INT '.' INT '.' INT
	public DayDataTypeElements getDayDataTypeAccess() {
		return pDayDataType;
	}
	
	public ParserRule getDayDataTypeRule() {
		return getDayDataTypeAccess().getRule();
	}
	
	//HourDataType ecore::EDate:
	//	INT ':' INT
	public HourDataTypeElements getHourDataTypeAccess() {
		return pHourDataType;
	}
	
	public ParserRule getHourDataTypeRule() {
		return getHourDataTypeAccess().getRule();
	}
	
	//Session:
	//	{Session} startingTime=HourDataType '-' endingTime=HourDataType 'in'
	//	room=[Room|EString] ':'
	//	events+=[Event|EString] (',' events+=[Event|EString])*;
	public SessionElements getSessionAccess() {
		return pSession;
	}
	
	public ParserRule getSessionRule() {
		return getSessionAccess().getRule();
	}
	
	//TalkSession:
	//	'TalkSession'
	//	name=EString ('chair' chair=Person)? ('abstract' abstract=EString)? ('papers' papers+=[Paper|EString] (','
	//	papers+=[Paper|EString])*)?;
	public TalkSessionElements getTalkSessionAccess() {
		return pTalkSession;
	}
	
	public ParserRule getTalkSessionRule() {
		return getTalkSessionAccess().getRule();
	}
	
	//Panel:
	//	'Panel'
	//	name=EString ('abstract' abstract=EString)? ('panelists' panelists+=Person (',' panelists+=Person)*)? ('moderators'
	//	moderators+=Person (',' moderators+=Person)*)?;
	public PanelElements getPanelAccess() {
		return pPanel;
	}
	
	public ParserRule getPanelRule() {
		return getPanelAccess().getRule();
	}
	
	//SRC:
	//	'SRC'
	//	name=EString ('abstract' abstract=EString)?;
	public SRCElements getSRCAccess() {
		return pSRC;
	}
	
	public ParserRule getSRCRule() {
		return getSRCAccess().getRule();
	}
	
	//Poster:
	//	'Poster'
	//	name=EString ('abstract' abstract=EString)?;
	public PosterElements getPosterAccess() {
		return pPoster;
	}
	
	public ParserRule getPosterRule() {
		return getPosterAccess().getRule();
	}
	
	//KeyNote:
	//	'KeyNote'
	//	name=EString ('abstract' abstract=EString)? ('speaker' speaker=Person)?;
	public KeyNoteElements getKeyNoteAccess() {
		return pKeyNote;
	}
	
	public ParserRule getKeyNoteRule() {
		return getKeyNoteAccess().getRule();
	}
	
	//Workshop:
	//	'Workshop'
	//	name=EString ('abstract' abstract=EString)? ('url' url=EString)? ('name' fullName=EString)? ('organizers'
	//	organizers+=Person (',' organizers+=Person)*)?;
	public WorkshopElements getWorkshopAccess() {
		return pWorkshop;
	}
	
	public ParserRule getWorkshopRule() {
		return getWorkshopAccess().getRule();
	}
	
	//Tutorial:
	//	'Tutorial'
	//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
	public TutorialElements getTutorialAccess() {
		return pTutorial;
	}
	
	public ParserRule getTutorialRule() {
		return getTutorialAccess().getRule();
	}
	
	//DoctoralSymposium:
	//	'DoctoralSymposium'
	//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
	public DoctoralSymposiumElements getDoctoralSymposiumAccess() {
		return pDoctoralSymposium;
	}
	
	public ParserRule getDoctoralSymposiumRule() {
		return getDoctoralSymposiumAccess().getRule();
	}
	
	//EducatorSymposium:
	//	'EducatorSymposium'
	//	name=EString ('abstract' abstract=EString)? ('organizers' organizers+=Person (',' organizers+=Person)*)?;
	public EducatorSymposiumElements getEducatorSymposiumAccess() {
		return pEducatorSymposium;
	}
	
	public ParserRule getEducatorSymposiumRule() {
		return getEducatorSymposiumAccess().getRule();
	}
	
	//Reception:
	//	'Reception'
	//	name=EString ('abstract' abstract=EString)?;
	public ReceptionElements getReceptionAccess() {
		return pReception;
	}
	
	public ParserRule getReceptionRule() {
		return getReceptionAccess().getRule();
	}
	
	//Clinic:
	//	'Clinic'
	//	name=EString ('abstract' abstract=EString)?;
	public ClinicElements getClinicAccess() {
		return pClinic;
	}
	
	public ParserRule getClinicRule() {
		return getClinicAccess().getRule();
	}
	
	//Lunch:
	//	'Lunch'
	//	name=EString ('abstract' abstract=EString)?;
	public LunchElements getLunchAccess() {
		return pLunch;
	}
	
	public ParserRule getLunchRule() {
		return getLunchAccess().getRule();
	}
	
	//CoffeeBreak:
	//	'CoffeeBreak'
	//	name=EString ('abstract' abstract=EString)?;
	public CoffeeBreakElements getCoffeeBreakAccess() {
		return pCoffeeBreak;
	}
	
	public ParserRule getCoffeeBreakRule() {
		return getCoffeeBreakAccess().getRule();
	}
	
	//Meeting:
	//	'Meeting'
	//	name=EString ('abstract' abstract=EString)?;
	public MeetingElements getMeetingAccess() {
		return pMeeting;
	}
	
	public ParserRule getMeetingRule() {
		return getMeetingAccess().getRule();
	}
	
	//Paper:
	//	{Paper} name=EString
	//	'authors' authors+=Person (',' authors+=Person)* ('abstract' abstract=EString)? ('preprint' preprint=EString)? ('kind'
	//	kind=Track)?;
	public PaperElements getPaperAccess() {
		return pPaper;
	}
	
	public ParserRule getPaperRule() {
		return getPaperAccess().getRule();
	}
	
	//Person:
	//	{Person} name=EString ('email' email=EString)? ('homepage' homepage=EString)?;
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//enum Track:
	//	PracticeAndInnovation='Practice and Innovation' | Research;
	public TrackElements getTrackAccess() {
		return eTrack;
	}
	
	public EnumRule getTrackRule() {
		return getTrackAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
